apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.datadoghq.com
    chart: datadog-operator
    targetRevision: 2.23.1
    helm:
      values: |
        datadog:
          apiKeyExistingSecret: datadog-secret
          site: us5.datadoghq.com
          clusterName: aks-productapi
          kubelet:
            tlsVerify: false
          logs:
            enabled: true
            containerCollectAll: true
          apm:
            enabled: true
          processAgent:
            enabled: true
          orchestratorExplorer:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
