apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pmelo1981/UnisabanaArq1Grupo2PatronesActividad3-productapi
    path: helm
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
        - values-acr.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: productapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
